version: '3.4'

services:

  redis:
    image: redis:5.0.1
    ports:
      - 6379:6379

  golang-api:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: golang-api
    ports:
      - 3333:3333
    links:
      - redis:redis
    depends_on:
      - redis
    env_file: env
